version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
hooks:
  AfterInstall:
    - location: scripts/setenv.sh
      timeout: 300
      runas: root

    - location: scripts/initialize.sh
      runas: root
